package Modelo;
// Generated 08-feb-2016 20:41:39 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Hotel generated by hbm2java
 */
public class Hotel  implements java.io.Serializable {


     private Integer idhotel;
     private Categoria categoria;
     private String nombre;
     private String ciudad;
     private Set habitacions = new HashSet(0);

    public Hotel() {
    }

    public Hotel(Categoria categoria, String nombre, String ciudad, Set habitacions) {
       this.categoria = categoria;
       this.nombre = nombre;
       this.ciudad = ciudad;
       this.habitacions = habitacions;
    }
   
    public Integer getIdhotel() {
        return this.idhotel;
    }
    
    public void setIdhotel(Integer idhotel) {
        this.idhotel = idhotel;
    }
    public Categoria getCategoria() {
        return this.categoria;
    }
    
    public void setCategoria(Categoria categoria) {
        this.categoria = categoria;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getCiudad() {
        return this.ciudad;
    }
    
    public void setCiudad(String ciudad) {
        this.ciudad = ciudad;
    }
    public Set getHabitacions() {
        return this.habitacions;
    }
    
    public void setHabitacions(Set habitacions) {
        this.habitacions = habitacions;
    }

     @Override
    public String toString(){
        return this.idhotel + " - " + this.nombre; 
    }



}


