package Modelo;
// Generated 08-feb-2016 20:41:39 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Huesped generated by hbm2java
 */
public class Huesped  implements java.io.Serializable {


     private String dni;
     private Habitacion habitacion;
     private String nombre;
     private String apellidos;
     private String direccion;
     private Date fechaNac;
     private String poblacion;
     private Character individual;

    public Huesped() {
    }

	
    public Huesped(String dni) {
        this.dni = dni;
    }
    public Huesped(String dni, Habitacion habitacion, String nombre, String apellidos, String direccion, Date fechaNac, String poblacion, Character individual) {
       this.dni = dni;
       this.habitacion = habitacion;
       this.nombre = nombre;
       this.apellidos = apellidos;
       this.direccion = direccion;
       this.fechaNac = fechaNac;
       this.poblacion = poblacion;
       this.individual = individual;
    }
   
    public String getDni() {
        return this.dni;
    }
    
    public void setDni(String dni) {
        this.dni = dni;
    }
    public Habitacion getHabitacion() {
        return this.habitacion;
    }
    
    public void setHabitacion(Habitacion habitacion) {
        this.habitacion = habitacion;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getApellidos() {
        return this.apellidos;
    }
    
    public void setApellidos(String apellidos) {
        this.apellidos = apellidos;
    }
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }
    public Date getFechaNac() {
        return this.fechaNac;
    }
    
    public void setFechaNac(Date fechaNac) {
        this.fechaNac = fechaNac;
    }
    public String getPoblacion() {
        return this.poblacion;
    }
    
    public void setPoblacion(String poblacion) {
        this.poblacion = poblacion;
    }
    public Character getIndividual() {
        return this.individual;
    }
    
    public void setIndividual(Character individual) {
        this.individual = individual;
    }
    
     @Override
    public String toString(){
        return this.nombre;
    }


}


